services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    env_file:
      - ./frontend/.env
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: runner
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
    env_file:
      - ./api/.env
    volumes:
      - api_uploads:/app/uploads
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  api_uploads:
